# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '9.0'
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

react_path = '../node_modules/react-native'
yoga_path = react_path + '/ReactCommon/yoga'

target 'HKAQI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  #React Pods
  pod 'React', :path => react_path, :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'yoga', :path => yoga_path

  # Pods for HKAQI
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crash'
  pod 'Firebase/Performance'
  pod 'Firebase/RemoteConfig'

  # Third party deps
  pod 'DoubleConversion', :podspec => react_path + '/third-party-podspecs/DoubleConversion.podspec'
  # pod 'GLog', :podspec => react_path + '/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => react_path + '/third-party-podspecs/Folly.podspec'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'


  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-google-analytics-bridge', :path => '../node_modules/react-native-google-analytics-bridge'

  pod 'Fabric'
  pod 'Crashlytics'
  pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == 'React'
      target.remove_from_project
    end
  end
end
